services:
  db:
    container_name: backend_db
    env_file:
      - .env.example
    image: postgres:17.3-alpine3.21
    ports:
      - '5432:5432'
    volumes:
      - backend_pg:/var/lib/postgresql/data
  redis:
    container_name: backend_redis
    image: redis:7.4.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - backend_redis:/data
  base_app:
    build:
      context: .
    depends_on:
      - db
      - redis
    env_file:
      - .env.example
    volumes:
      - backend_gems:/usr/local/bundle
      - .:/backend
  app:
    extends:
      service: base_app
    command: bin/dev
    container_name: backend_app
    depends_on:
      - sidekiq
    ports:
      - '3000:3000'
  sidekiq:
    extends:
      service: base_app
    command: ["bundle", "exec", "sidekiq"]
    container_name: backend_sidekiq

volumes:
  backend_gems:
  backend_pg:
  backend_redis:
